### ISSUE TITLE
这里的代码有点问题

### ISSUE THREAD

**Issue by xiaoxiyao** [UzkiS/vuEPG#1]
https://github.com/LemoFire/vuEPG/blob/601b0e528e041377200305eaed81c58d871edbe3/src/lib/service.ts#L234
itemArray为空取第一个还有意义吗

**Comment by UzkiS** [comment]
比如你进入了其他路由，这个路由不存在任何可选焦点，itemArray就被清空了，这个时候就需要通过这段代码清空currentItem，因为其实际已经不存在了
现在想一下为什么 #2 中一定需要在挂载时手动移动到默认焦点也是这个原因，如果切换了路由，新路由中存在其他item，这时候currentItem中存放的还是上一个页面的Item，并不能使用，所以手动move到默认焦点是必要的

**Comment by xiaoxiyao** [comment]
> 比如你进入了其他路由，这个路由不存在任何可选焦点，itemArray就被清空了，这个时候就需要通过这段代码清空currentItem，因为其实际已经不存在了 现在想一下为什么 #2 中一定需要在挂载时手动移动到默认焦点也是这个原因，如果切换了路由，新路由中存在其他item，这时候currentItem中存放的还是上一个页面的Item，并不能使用，所以手动move到默认焦点是必要的

这个时候应该直接清空currentItem就行了，下面判断没有currentItem就给currentItem赋值，会让人误解

**Comment by UzkiS** [comment]
> > 比如你进入了其他路由，这个路由不存在任何可选焦点，itemArray就被清空了，这个时候就需要通过这段代码清空currentItem，因为其实际已经不存在了 现在想一下为什么 #2 中一定需要在挂载时手动移动到默认焦点也是这个原因，如果切换了路由，新路由中存在其他item，这时候currentItem中存放的还是上一个页面的Item，并不能使用，所以手动move到默认焦点是必要的
> 
> 这个时候应该直接清空currentItem就行了，下面判断没有currentItem就给currentItem赋值，会让人误解

路由更新仅是一个例子，包括手动移除Item也会导致itemArray被清空。代码逻辑上之后可以考虑在更新itemArray时判断itemArray是否为空，如果为空就清空currentItem，感谢建议
