### ISSUE TITLE
第一次焦点移动问题

### ISSUE THREAD

**Issue by xiaoxiyao** [UzkiS/vuEPG#2]
初始化时并没有元素获取焦点，当使用任意方向键移动焦点时，会自动将第一个EPGItem作为当前焦点来移动，移动到了下一个item，直接跳过了第一个item。
建议第一次移动焦点时，如果当前没有焦点，则自动聚焦第一个item

**Comment by UzkiS** [comment]
感谢反馈！
会自动将第一个 EPGItem 作为当前焦点来移动是为了避免一些问题的发生
目前构想的使用方式就是需要在onMounted时手动进行第一次聚焦（参照旧版EPG）

关于如果没有焦点自动聚焦第一个item的功能，如果没有记错也是存在一些问题所以没有做
等我有空的话会再次考虑是否加入，当然如果你先搞定了直接发pull request也是可以的 :)

**Comment by xiaoxiyao** [comment]
感谢解答！旧版EPG没有用过🤣，我也是最近刚学vue，我先手动聚焦吧
